### ISSUE TITLE
replace_text.py >>> def change_ui_font(path)

### ISSUE THREAD

**Issue by Naunter** [BDO-CnHope/bdocn_client#8]
replace_text.py >>> def change_ui_font(path)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "replace_text.py", line 19, in change_ui_font
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 954, in _bootstrap_inner
  File "threading.py", line 892, in run
  File "ui4.py", line 345, in start_button
  File "replace_text.py", line 19, in change_ui_font
OSError: [Errno 9] Bad file descriptor

_Originally posted by @Vdc-K in https://github.com/BDO-CnHope/bdocn_client/issues/7#issuecomment-847161409_

**Comment by Naunter** [comment]
no reply, close
